# Generated by Django 4.1.3 on 2023-06-25 08:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_followerscount'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
