# Generated by Django 4.1.3 on 2023-06-25 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='icon',
            field=models.ImageField(default='static/images/blank-profile-picture.jpeg', null=True, upload_to=''),
        ),
    ]
